### ISSUE TITLE
osCommerce config keys helper Missing testparameter in pw 4.0.8

### ISSUE THREAD

**Issue by Fredrik-H-Laastad** [DIBS-Payment-Services/OsCommerce#1]
osCommerce config keys helper is missing the parameter 'MODULE_PAYMENT_DIBS_TESTMODE' which renders the module in a constant testmode

Added screenshots of missing and fixed dibs.php file

![missing](https://cloud.githubusercontent.com/assets/8394150/3855861/072d4aa4-1eec-11e4-99ed-b24f76ecc1d3.PNG)
![fixed](https://cloud.githubusercontent.com/assets/8394150/3855862/0731d8ee-1eec-11e4-99a3-3695293a094f.PNG)

**Comment by maxwhite** [comment]
done in latest release 4.0.9.1
