### ISSUE TITLE
Remove Checkout type from options

### ISSUE THREAD

**Issue by livarb** [DIBS-Payment-Services/OsCommerce#2]
![image](https://cloud.githubusercontent.com/assets/3617256/5507841/3fdb1dbc-87a7-11e4-9ce2-351459adc9bc.png)

Seems like this option has lost it's use. According to DIBS customer service, the standard payment window support works well on mobile devices. So then it's no point in setting it to Mobile or Auto. I tried auto, and payments via mobile devices was obviously router to a different backend. The other back-end did not register customer and order information for the transaction in DIBS' system. This is a huge drawback for finding transactions in DIBS. It is obvious that the mobile payments are handled by a different back-end because e-mail notifications of transactions have a different from-address as well.

![image](https://cloud.githubusercontent.com/assets/3617256/5507862/7ab2bd32-87a7-11e4-8929-0dc819468608.png)

**Comment by maxwhite** [comment]
done in latest release 4.0.9.1
