### ISSUE TITLE
Unstable saving of DIBS-reference in comment-field of osCommerce-order

### ISSUE THREAD

**Issue by livarb** [DIBS-Payment-Services/OsCommerce#3]
Exactly what reference to the DIBS-transaction is stored in osCommerce will vary.
When "Set order status" is set to "standard", it will only append " transaction=<transaction>" to the end of the comment-string.
If "Set order status" is set to a specific Order status in osCommerce, it will store "[DIBS Order ID: <order id>]", and the transaction number is not added.
Since the transcation number is unique, while order number can refer to multiple (attempted) transactions, I'd prefer that both are stored in osCommerce.

**Comment by maxwhite** [comment]
done in latest release 4.0.9.1
